{% set data = load_setup_py_data() %}

package:
  name: mlplumber
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - sklearn-pandas>=2.0.0
    - baikal>=0.4.1

  run:
    - python
    - sklearn-pandas>=2.0.0
    - baikal>=0.4.1

test:
  imports:
    - mlplumber

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}

summary: {{ data['description'] }}