name: Upload Python Package

on:
  push:
    tags:
      - 'v*'

jobs:

  # release:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 50
  #   - uses: fregante/release-with-changelog@v3
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}

  deploy_pypi_test:
    name: Test PYPI
    # needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Python Package
        uses: mariamrf/py-package-publish-action@v1.0.0
        with:
          python_version: '3.x'
        env:
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
          TWINE_USERNAME: __token__

  
